update

diff --git a/switch-home b/switch-home
--- a/switch-home
+++ b/switch-home
@@ -1,3 +1,8 @@
 #!/bin/sh
-#
-nix build '.?submodule=1#homeConfigurations.ninjin.activationPackage' --extra-experimental-features 'nix-command flakes' && result/activate 
+
+if [ "$1" == "" ]; then
+  echo "Error: host name required"
+  exit 1
+fi
+
+nix build ".?submodule=1#homeConfigurations.${1}.activationPackage" --extra-experimental-features 'nix-command flakes' && result/activate 
